import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";

import { Inter_Tight } from "next/font/google";
import "./globals.scss";

const interTight = Inter_Tight({
  subsets: ["cyrillic"],
  weight: ["300", "400", "500"],
  variable: "--finterTight",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="uk" className={interTight.variable}>
      <body style={{ overflowX: "hidden" }}>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}

// src/components/Footer/Footer.jsx
